### ISSUE TITLE
added one

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlightjs-supercollider#4]
I only asked for the resolution since you closed the issue without pushing any updates.

Thanks.  There was no need to lock. :-)

**Comment by mossheim** [comment]
please do not open new issues just to leave passive-aggressive comments @yyyc514

**Comment by joshgoebel** [comment]
_Sorry, but there was **no need** to lock the previous comment._  From my perspective it's you who've [perhaps] been a little something from the beginning - though I try not to judge or get too annoyed at such things.  I should have just let it go, but sometimes... 

I only asked for the resolution since (from my perspective) you closed the comment without taking any action at all, so asking why seemed a reasonable request.

**Comment by joshgoebel** [comment]
Please don't lock issues for no real reason in the future if you don't want to temp people to misbehave and find some other channel to comment.  ;-)

And Happy Holidays.  **I'm writing this off as a simple misunderstanding  on both sides.  No hard feelings.**
